[package]
name = "biterator"
version = "0.1.0"
edition = "2021"
description = "A bad implementation of Bidirectional Iterator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
